server:
  port: 8083

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: siraj123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: inventory-service-group

      auto-offset-reset: earliest

logging:
  level:
    org.hibernate.SQL: DEBUG