spring.application.name=quiz-service
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5432/quizdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

spring.security.oauth2.client.registration.question-service.provider=authorization-server
spring.security.oauth2.client.registration.question-service.client-id=quiz-service
spring.security.oauth2.client.registration.question-service.client-secret=quiz-service-secret
spring.security.oauth2.client.registration.question-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.question-service.scope=question.generate,question.read,question.evaluate

spring.security.oauth2.client.provider.authorization-server.token-uri=http://localhost:9000/oauth2/token