server:
  port: 8085

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: postgres
    password: siraj123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    org.springframework.kafka: INFO